email:
  username: "onezerobinaryltd@gmail.com"
  password: "t4pcAUNWC2"
  host: "smtp.gmail.com"
  addr: "smtp.gmail.com:587"
  from: "PulseRescue"

service:
  urlLocal: "http://localhost:8800/confirm?k="
  urlRemote: "http://172.104.230.81/confirm?k="
