// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	email.proto

It has these top-level messages:
	EmailResponse
	Recipient
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type EmailResponse struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *EmailResponse) Reset()                    { *m = EmailResponse{} }
func (m *EmailResponse) String() string            { return proto1.CompactTextString(m) }
func (*EmailResponse) ProtoMessage()               {}
func (*EmailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EmailResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Recipient struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Template int32  `protobuf:"varint,3,opt,name=template" json:"template,omitempty"`
}

func (m *Recipient) Reset()                    { *m = Recipient{} }
func (m *Recipient) String() string            { return proto1.CompactTextString(m) }
func (*Recipient) ProtoMessage()               {}
func (*Recipient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Recipient) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Recipient) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Recipient) GetTemplate() int32 {
	if m != nil {
		return m.Template
	}
	return 0
}

func init() {
	proto1.RegisterType((*EmailResponse)(nil), "proto.EmailResponse")
	proto1.RegisterType((*Recipient)(nil), "proto.Recipient")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EmailService service

type EmailServiceClient interface {
	// Send a Email to an Account returns Response
	SendEmail(ctx context.Context, in *Recipient, opts ...grpc.CallOption) (*EmailResponse, error)
}

type emailServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmailServiceClient(cc *grpc.ClientConn) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) SendEmail(ctx context.Context, in *Recipient, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := grpc.Invoke(ctx, "/proto.EmailService/SendEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EmailService service

type EmailServiceServer interface {
	// Send a Email to an Account returns Response
	SendEmail(context.Context, *Recipient) (*EmailResponse, error)
}

func RegisterEmailServiceServer(s *grpc.Server, srv EmailServiceServer) {
	s.RegisterService(&_EmailService_serviceDesc, srv)
}

func _EmailService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Recipient)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmailService/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendEmail(ctx, req.(*Recipient))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _EmailService_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email.proto",
}

func init() { proto1.RegisterFile("email.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xc1, 0x0a, 0x82, 0x40,
	0x14, 0x45, 0xb3, 0x32, 0xf2, 0x55, 0x10, 0x0f, 0x17, 0xe2, 0x2a, 0x6c, 0xd3, 0xca, 0x45, 0xd1,
	0x27, 0xf8, 0x03, 0xe3, 0x17, 0x98, 0xde, 0xc5, 0x90, 0xce, 0x0c, 0x3a, 0xf4, 0xfd, 0xe1, 0x9b,
	0x10, 0x5a, 0xcd, 0x9c, 0xc3, 0xe3, 0xde, 0x4b, 0x07, 0x0c, 0x8d, 0xee, 0x4b, 0x37, 0x5a, 0x6f,
	0x39, 0x96, 0xa7, 0xb8, 0xd2, 0xa9, 0x9a, 0xad, 0xc2, 0xe4, 0xac, 0x99, 0xc0, 0x4c, 0xdb, 0xd6,
	0x76, 0xc8, 0xa2, 0x4b, 0x74, 0x8b, 0x95, 0xfc, 0x8b, 0x9a, 0x12, 0x85, 0x56, 0x3b, 0x0d, 0xe3,
	0x39, 0xa5, 0x58, 0x72, 0xe4, 0x22, 0x51, 0x01, 0x66, 0xeb, 0xed, 0x1b, 0x26, 0x5b, 0x07, 0x2b,
	0xc0, 0x39, 0xed, 0x3d, 0x06, 0xd7, 0x37, 0x1e, 0xd9, 0x46, 0x02, 0x17, 0xbe, 0x57, 0x74, 0x94,
	0xe6, 0x1a, 0xe3, 0x47, 0xb7, 0xe0, 0x27, 0x25, 0x35, 0x4c, 0x27, 0x8e, 0xcf, 0x61, 0x65, 0xb9,
	0xd4, 0xe6, 0xe9, 0xcf, 0xfc, 0xad, 0x2d, 0x56, 0xaf, 0x9d, 0xe8, 0xc7, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x3b, 0x5f, 0x02, 0x4a, 0xdd, 0x00, 0x00, 0x00,
}
